language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install asv virtualenv
  - cp .asv-machine.json ~
script:
  - py.test
  - asv run --show-stderr
notifications:
  email: false
