name: Run benchmarks

on: [push, pull_request]

jobs:

  benchmarks:

    runs-on: ubuntu-20.04

    steps:

      - name: Checkout SymPy
        uses: actions/checkout@v3
        with:
          repository: sympy/sympy
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv asv

      - name: Setup access to branches
        run: |
          git submodule add https://github.com/sympy/sympy_benchmarks.git
          git remote add upstream https://github.com/sympy/sympy.git
          git fetch upstream master
          git fetch upstream 1.11

      - name: Configure benchmarks
        run: asv machine --yes --config asv.conf.actions.json

      - name: Run benchmarks
        run: asv run --config asv.conf.actions.json --quick